#%RAML 1.0 NamedExample
{
   "projectId": "1233456",
   "projectName" : "Union Bank of Nigeria Plc-UKN/Nigeri",
   "productId": "1233456",
   "productName": "123445",
   "functionId": "",
   "functionName": "",
   "regionId": "",
   "regionName": "",
   "subsidiaryId": "",
   "subsidiaryName": "",
   "costcentreId": "",
   "costcentreName": "",
   "customerId": "",
   "customerName": "",   
}