#%RAML 1.0 NamedExample
[{
 "invoiceId": "11831306",
 "kimbleCreditNoteNumber": "CA123445",
 "invoiceDate": "2020-01-01",
 "quantity": 1,
 "rate": 100,
 "orderLineId": 1,
 "creditReason": "Fin RA-001",
 "employeeId": "1433865"
}]