#%RAML 1.0 NamedExample
[{
  "salesOrderId": "12041616",
  "kimbleInvNumber": "SI2018AE20000999",
  "invoiceDate": "2020-05-14",
  "rate": 101,
  "quantity": 1,
  "description": "comments",
  "orderLineNumber": 1,
  "notes": "notes",
  "poReference": "po reference"
}]