#%RAML 1.0 DataType

displayName: Assignments Object
properties:
  projectId:
    type: string
    required: true
    description: Project Id
  projectName:
    type: string
    required: true
    description: Project Name 
  productId:
    type: string
    required: true
    description: Product Id
  productName:
    type: string
    required: true
    description: Product Name
  functionId:
    type: string
    default: ""
    required: true
    description: Function Id
  functionName:
    type: string
    default: ""
    required: true
    description: Function Name
  regionId:
    type: string
    default: ""
    required: true
    description: Region Id
  regionName:
    type: string
    required: true
    description: Region Name
  subsidiaryId:
    type: string
    default: ""
    required: true
    description:  Subsidiary Id
  subsidiaryName:
    type: string
    default: ""
    required: true
    description:  Subsidiary Name
  costcentreId:
    type: string
    default: ""
    required: true
    description: Cost Centre Id
  costcentreName:
    type: string
    default: ""
    required: true
    description: Cost Centre Name
  customerId:
    type: string
    default: ""
    required: true
    description: Customer Id
  customerName:
    type: string
    default: ""
    required: true
    description: Customer Name     